// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAn9iwk0z-U9g1UONR3oLSPsHkmKbDoLz0',
    appId: '1:294407978861:web:b78e67dd53ba9cca6d2464',
    messagingSenderId: '294407978861',
    projectId: 'travel-30bdb',
    authDomain: 'travel-30bdb.firebaseapp.com',
    storageBucket: 'travel-30bdb.appspot.com',
    measurementId: 'G-8D0VLTK4KG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXovd-aQ5tXP9CUq4EpviEn2oQ47mtNb8',
    appId: '1:294407978861:android:d1fa811427c808fc6d2464',
    messagingSenderId: '294407978861',
    projectId: 'travel-30bdb',
    storageBucket: 'travel-30bdb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1rqUkqxus8yTP1E7Fn4O6UjmuUOmhTD4',
    appId: '1:294407978861:ios:648a508414725ef66d2464',
    messagingSenderId: '294407978861',
    projectId: 'travel-30bdb',
    storageBucket: 'travel-30bdb.appspot.com',
    iosBundleId: 'com.example.flutterTravel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1rqUkqxus8yTP1E7Fn4O6UjmuUOmhTD4',
    appId: '1:294407978861:ios:e83778fe1f025c4a6d2464',
    messagingSenderId: '294407978861',
    projectId: 'travel-30bdb',
    storageBucket: 'travel-30bdb.appspot.com',
    iosBundleId: 'com.example.flutterTravel.RunnerTests',
  );
}
